### ISSUE TITLE
Graphics for MM: Expression & Origami

### ISSUE THREAD

**Issue by Burhan-Q** [Burhan-Q/MakerMask#9]
- Erika requested mask logos from Erin
- [x] MM: Expression
- [x] MM: Origami

**Comment by Burhan-Q** [comment]
Should expect something this week

**Comment by EurekaB42** [comment]
Actively in works

**Comment by Burhan-Q** [comment]
Images ready for review
@songerj and @EurekaB42 (and group) agree the Origami is good
Expression is a bit funky, probably needs some updating
- chin area could be trimmed/thinned
- shadowing on mask might help, pleating area
- white lips seem strange?
- shift the window area to be centered on the mask around the nose
- current color is dark green, going to ask for color change

**Comment by Burhan-Q** [comment]
MM: Origami is being updated by Margaret

**Comment by EurekaB42** [comment]
MM: Expression feedback has been shared with Erin.  Hoping to close out this week.

**Comment by Burhan-Q** [comment]
Artist trying to find time to work on, expecting to see something in the next few days
